version: "3"
services:
  db:
    container_name: db
    image: mariadb:10.4
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"

  artganizer:
    image: ghcr.io/tekofx/artganizer
    container_name: artganizer
    env_file: .env
    volumes:
      - ./backend/data:/app/backend/data
    ports:
      - 3000:3000 # Web
      - 3001:3001 # Backend
    depends_on:
      - db
    restart: unless-stopped
    command: tail -F anything
