version: "3"
services:
  db:
    container_name: db
    image: mariadb:10.4
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20

  artganizer:
    container_name: artganizer
    build: .
    image: artganizer
    env_file: .env
    volumes:
      - ./backend/data:/app/backend/data
    ports:
      - 3000:3000 # Web
      - 3001:3001 # Backend
    depends_on:
      db:
        condition: service_healthy
